routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//user controller for admin
Route::namespace('Admin')->prefix('admin')->middleware('auth')->name('admin.')->group(function(){
    Route::resource('/users', 'UserController', ['except' => ['show', 'create', 'store']]);
});

//shop controller for admin
Route::namespace('Admin')->prefix('admin')->middleware('auth')->name('admin.')->group(function(){
    Route::resource('/shops', 'ShopController'); 
});

//shop controller for normal user
Route::resource('/shops', 'ShopsController');

//All people can search the shop
Route::get('/search','ShopsController@search');

app/Shop.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Shop extends Model
{
    public function user() {
        return $this->belongsTo('App\User');
    }

    public function category() {
        return $this->belongsTo('App\Category');
    }

    public function getOwner($id) {
        return DB::table('users')->where('id', $id)->pluck('name');
    }

    public function getCategory($id) {
        return DB::table('categories')->where('id', $id)->pluck('name');
    }
}

app/Http/Controllers/Admin/ShopController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Shop;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class ShopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Gate::allows('admin-only', Auth::user())) {
            $shops = Shop::orderBy('created_at', 'desc')->paginate(10);
            return view('admin.shops.index')->with('shops', $shops);
        }
        return redirect()->route('login')->with('warning', 'Please login as Admin');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.shops.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|max:50',
            'code' => 'required|max:10',
            'description' => 'nullable|max:50',
            'lotnumber' => 'required|max:10',
            'zone' => 'required',
            'floorlevel' => 'required',
            'category' => 'required',
            'shop_image' => 'image|nullable|max:1999'
        ]);

        // Handle file upload
        if($request->hasFile('shop_image')){
            // Get filename with the extension
            $filenameWithExt = $request->file('shop_image')->getClientOriginalName();
            // Get just filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // Get just extension
            $extension = $request->file('shop_image')->getClientOriginalExtension();
            // filename to store
            $filenameToStore = $filename.'_'.time().'.'.$extension;
            // Upload Image
            $path = $request->file('shop_image')->storeAs('public/shop_images', $filenameToStore);
        } else {
            $filenameToStore = 'no-image-available.png';
        }

        // Create Post
        $shop = new Shop;
        $shop->name = $request->input('name');
        $shop->code = $request->input('code');
        $shop->description = $request->input('description');
        $shop->lotnumber = $request->input('lotnumber');
        $shop->zone = $request->input('zone');
        $shop->floorlevel = $request->input('floorlevel');
        $shop->category_id = $request->input('category');
        $shop->merchant_id = auth()->user()->id;
        $shop->image = $filenameToStore;
        $shop->save();

        return redirect('/admin/shops')->with('success', 'New Shop Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $shop = Shop::find($id);
        return view('admin.shops.show')->with('shop', $shop);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $shop = Shop::find($id);
        return view('admin.shops.edit')->with('shop', $shop);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:50',
            'code' => 'required|max:10',
            'description' => 'nullable|max:50',
            'lotnumber' => 'required|max:10',
            'zone' => 'required',
            'floorlevel' => 'required',
            'category' => 'required',
            'merchant_id' => 'required|numeric',
            'shop_image' => 'image|nullable|max:1999'
        ]);

        // Handle file upload
        if($request->hasFile('shop_image')){
            // Get filename with the extension
            $filenameWithExt = $request->file('shop_image')->getClientOriginalName();
            // Get just filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // Get just extension
            $extension = $request->file('shop_image')->getClientOriginalExtension();
            // filename to store
            $filenameToStore = $filename.'_'.time().'.'.$extension;
            // Upload Image
            $path = $request->file('shop_image')->storeAs('public/shop_images', $filenameToStore);
        } else {
            $filenameToStore = 'no-image-available.png';
        }

        // Create Post
        $shop = Shop::find($id);
        $shop->name = $request->input('name');
        $shop->code = $request->input('code');
        $shop->description = $request->input('description');
        $shop->lotnumber = $request->input('lotnumber');
        $shop->zone = $request->input('zone');
        $shop->floorlevel = $request->input('floorlevel');
        $shop->category_id = $request->input('category');
        $shop->merchant_id = $request->input('merchant_id');
        if($request->hasFile('shop_image')) {
            $shop->image = $filenameToStore;
        }
        $shop->save();

        return redirect('/admin/shops')->with('success', 'Shop Info Edited');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $shop = Shop::find($id);
        if($shop->image != 'no-image-available.png'){
            // Delete Image
            Storage::delete('public/shop_images/'.$shop->image);
        }
        $shop->delete();
        return redirect('/admin/shops')->with('success', 'Shop Deleted');
    }
}

app/Http/Controllers/ShopsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use App\Shop;
use App\User;

class ShopsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $categories = [];

        if(Gate::allows('merchant-only', $user)) {
            $ownedShops = Shop::where('merchant_id', $user->id)->get();
            foreach($ownedShops as $shop) {
                $category = $shop->category()->get();
                array_push($categories, $category);
            }
            return view('shops.index')->with('categories', $categories);
        }

        $shops = Shop::all();
        foreach($shops as $shop) {
            $category = $shop->category()->get();
            array_push($categories, $category);
        }
        return view('shops.index')->with('categories', $categories);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $shops = Shop::where('category_id', $id)->orderBy('name')->get();
        $category = DB::table('categories')->where('id', $id)->get()->pluck('name');
        return view('shops.show')->with('shops', $shops)->with('category', $category);
    }

    public function edit($id)
    {
        $user = Auth::user();
        if(Gate::allows('merchant-only', $user)) {
            $shop = Shop::find($id);
            if($shop->merchant_id == $user->id) {
                return view('shops.edit')->with('shop', $shop);
            }
            return redirect()->route('login')->with('warning', 'You cannot edit others people shop');
        }
        return redirect()->route('login')->with('warning', 'Please login as Merchant');
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|max:50',
            'description' => 'nullable|max:50',
            'lotnumber' => 'required|max:10',
            'zone' => 'required',
            'floorlevel' => 'required',
            'category' => 'required',
            'shop_image' => 'image|nullable|max:1999'
        ]);

        // Handle file upload
        if($request->hasFile('shop_image')){
            // Get filename with the extension
            $filenameWithExt = $request->file('shop_image')->getClientOriginalName();
            // Get just filename
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            // Get just extension
            $extension = $request->file('shop_image')->getClientOriginalExtension();
            // filename to store
            $filenameToStore = $filename.'_'.time().'.'.$extension;
            // Upload Image
            $path = $request->file('shop_image')->storeAs('public/shop_images', $filenameToStore);
        } else {
            $filenameToStore = 'no-image-available.png';
        }

        // Create Post
        $shop = Shop::find($id);
        $shop->name = $request->input('name');
        $shop->description = $request->input('description');
        $shop->lotnumber = $request->input('lotnumber');
        $shop->zone = $request->input('zone');
        $shop->floorlevel = $request->input('floorlevel');
        $shop->category_id = $request->input('category');
        $shop->merchant_id = auth()->user()->id;
        if($request->hasFile('shop_image')) {
            $shop->image = $filenameToStore;
        }
        $shop->save();

        return redirect('/shops')->with('success', 'Shop Info Updated');
    }

    public function search(Request $request)
    {
        $search = $request->input('search');

        return view('welcome',compact('search'));
    }
}

resources/views/admin/shops/create.blade.php
@extends('layouts.app')

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Fill in Shop Information</div>
                <div class="panel-body">
                    {{ Form::open(['action' => 'Admin\ShopController@store', 'method' => 'POST', 'enctype' => 'multipart/form-data']) }}
                        <div class="form-group">
                            {{Form::label('name', 'Name')}}
                            {{Form::text('name', '', ['class' => 'form-control', 'placeholder' => 'Shop Name'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('merchant_id', 'Merchant ID')}}
                            {{Form::text('merchant_id', '', ['class' => 'form-control', 'placeholder' => 'User ID'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('code', 'Code')}}
                            {{Form::text('code', '', ['class' => 'form-control', 'placeholder' => 'Code'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('lotnumber', 'Lot Number')}}
                            {{Form::text('lotnumber', '', ['class' => 'form-control', 'placeholder' => 'Lot Number'])}}
                        </div>
                        <div class="form-group">
                            {{ Form::label('zone', 'Zone') }}
                            {{ Form::select('zone', array('0' => 'New Wing', '1' => 'Old Wing'), '0', ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('floorlevel', 'Floor Level') }}
                            {{ Form::select('floorlevel', array('G' => 'G', 'F1' => 'F1', 'F2' => 'F2', 'F3' => 'F3'), 'G',
                            ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('category', 'Category') }}
                            {{ Form::select('category', array(
                                '1' => 'Amenities', '2' => 'Anchors',  '3' => 'Beauty and Healthcare', 
                                '4' => 'Books', '5' => 'Convenience Store', '6' => 'Digital Lifestyle and Photography',
                                '7' => 'Foods and Beverages', '8' => 'Footwear', '9' => 'Fitness',
                                '10' => 'Leisure and Entertainment', '11' => 'Shirts and Fashion', '12' => 'Haircare/Salon',
                                '13' => 'Hobbies', '14' => 'Others'), '1', ['class' => 'form-control']) }}
                        </div>
                        <div class='form-group'>
                            {{ Form::label('description', 'Description') }}
                            {{ Form::textarea('description', null, ['class' => 'form-control', 'style' => 'resize:none']) }}
                        </div>
                        <div class='form-group'>
                            {{ Form::label('shop_image', 'Image') }}
                            {{ Form::file('shop_image') }}
                        </div>
                        {{ Form::submit('Submit', ['class' => 'btn btn-primary']) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/shops/edit.blade.php
@extends('layouts.app')

@section('content')
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Shop Information (Admin-only)</div>
                <div class="panel-body">
                    {{ Form::open(['action' => ['Admin\ShopController@update', $shop->id], 'method' => 'POST', 'enctype' => 'multipart/form-data']) }}
                        <div class="form-group">
                            {{Form::label('name', 'Name')}}
                            {{Form::text('name', $shop->name, ['class' => 'form-control', 'placeholder' => 'Shop Name'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('merchant_id', 'Merchant ID')}}
                            {{Form::text('merchant_id', $shop->merchant_id, ['class' => 'form-control', 'placeholder' => 'User ID'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('code', 'Code')}}
                            {{Form::text('code', $shop->code, ['class' => 'form-control', 'placeholder' => 'Code'])}}
                        </div>
                        <div class="form-group">
                            {{Form::label('lotnumber', 'Lot Number')}}
                            {{Form::text('lotnumber', $shop->lotnumber, ['class' => 'form-control', 'placeholder' => 'Lot Number'])}}
                        </div>
                        <div class="form-group">
                            {{ Form::label('zone', 'Zone') }}
                            {{ Form::select('zone', array('0' => 'New Wing', '1' => 'Old Wing'), $shop->zone, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('floorlevel', 'Floor Level') }}
                            {{ Form::select('floorlevel', array('G' => 'G', 'F1' => 'F1', 'F2' => 'F2', 'F3' => 'F3'), $shop->floorlevel, 
                            ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('category', 'Category') }}
                            {{ Form::select('category', array(
                                '1' => 'Amenities', '2' => 'Anchors',  '3' => 'Beauty and Healthcare', 
                                '4' => 'Books', '5' => 'Convenience Store', '6' => 'Digital Lifestyle and Photography',
                                '7' => 'Foods and Beverages', '8' => 'Footwear', '9' => 'Fitness',
                                '10' => 'Leisure and Entertainment', '11' => 'Shirts and Fashion', '12' => 'Haircare/Salon',
                                '13' => 'Hobbies', '14' => 'Others'), $shop->category_id, ['class' => 'form-control']) }}
                        </div>
                        <div class='form-group'>
                            {{ Form::label('description', 'Description') }}
                            {{ Form::textarea('description', $shop->description, ['class' => 'form-control', 'style' => 'resize:none']) }}
                        </div>
                        <div class='form-group'>
                            {{ Form::label('shop_image', 'Image') }}
                            {{ Form::file('shop_image') }}
                        </div>
                        {{ Form::hidden('_method', 'PUT') }}
                        {{ Form::submit('Update', ['class' => 'btn btn-primary']) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/shops/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title text-left">Manage Shop
                        <a href="{{ route('admin.shops.create') }}" class="pull-right">
                            <button type="button" class="btn btn-primary btn-sm">Add New Shop</button>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    @if($shops->count() > 0)
                        <table class='table'>
                            <thead>
                            <tr>
                                <th scope='col'>Name</th>
                                <th scope='col'>Code</th>
                                <th scope='col'>Categories</th>
                                <th scope='col'>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($shops as $shop)
                                <tr>
                                    <th><a href="{{ route('admin.shops.show', $shop->id) }}">{{ $shop->name }}</a></th>
                                    <th>{{ $shop->code }}</th>
                                    <th>{{ implode(', ', $shop->getCategory($shop->category_id)->toArray()) }}</th>
                                    <th>
                                        <div class="row">
                                            <a href="{{ route('admin.shops.edit', $shop->id) }}" class="col-xs-3">
                                                <button type="button" class="btn btn-primary btn-sm">Edit</button>
                                            </a>
                                            <form action="{{ route('admin.shops.destroy', $shop->id) }}" method="POST" class="col-xs-3">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </div>
                                    </th>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div>No Shop In Record</div>
                    @endif
                    {{ $shops-> links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/shops/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <a href='/admin/shops' class='btn btn-default'>Go Back</a>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">Shop Details</div>
                </div>
                <div class="panel-body">
                    <img class="col-md-6" style="width:50%" src="/storage/shop_images/{{$shop->image}}" alt="responsive-image">
                    <div class="col-md-6">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <th>Name</th>
                                    <td>{{ $shop->name }}</td>
                                </tr>
                                <tr>
                                    <th>Code</th>
                                    <td>{{ $shop->code }}</td>
                                </tr>
                                <tr>
                                    <th>Lot Number</th>
                                    <td>{{ $shop->lotnumber }}</td>
                                </tr>
                                <tr>
                                    <th>Zone</th>
                                    @if($shop->zone == '0')
                                        <td>New Wing</td>
                                    @else
                                        <td>Old Wing</td>
                                    @endif
                                </tr>
                                <tr>
                                    <th>Floor Level</th>
                                    <td>{{ $shop->floorlevel }}</td>
                                </tr>
                                <tr>
                                    <th>Category</th>
                                    <td>{{ implode(', ', $shop->getCategory($shop->category_id)->toArray()) }}</td>
                                </tr>
                                <tr>
                                    <th>Merchant Name</th>
                                    <td>{{ implode(', ', $shop->getOwner($shop->merchant_id)->toArray()) }}</td>
                                </tr>
                                <tr>
                                    <th>Merchant ID</th>
                                    <td>{{ $shop->merchant_id }}</td>
                                </tr>
                                <tr>
                                    <th>Actions</th>
                                    <td>
                                        <a href="{{ route('admin.shops.edit', $shop->id) }}" class="col-xs-3">
                                            <button type="button" class="btn btn-primary btn-sm">Edit</button>
                                        </a>
                                        <form action="{{ route('admin.shops.destroy', $shop->id) }}" method="POST" class="col-xs-3">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection